services:
  user-app:
    container_name: user-app
    image: user-microservice:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5002:5002
      - 9101:9101
    expose:
      - '9101'
    env_file:
      - ./.env.docker
    networks:
      - coffeedoor-network

networks:
  coffeedoor-network:
      external: true
